### ISSUE TITLE
feature: could we allow for rules yaml to be driven by dot file?

### ISSUE THREAD

**Issue by ChrisJBurns** [krupa-dev/manplan#2]
Currently users have to specify a `sdk-rules.yaml` file that contains the rules. To avoid users having to run `manplan` with a file argument everytime (and having to find a home for the file), we should probably provide the option to use a default dotfile.

This means that if a user simply runs `manplan`, then because there is no file argument provided, it will look for a default dotfile (`.sdk-rules.yaml`) in the users home.

**Comment by GJKrupa** [comment]
Fix in https://github.com/krupa-dev/manplan/releases/tag/v0.1.4
